// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ChessEngineKitFFI)
import ChessEngineKitFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_engine_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_engine_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureEngineFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol ChessGameProtocol: AnyObject, Sendable {
    
    func aiMove(depth: UInt8) throws  -> MoveData
    
    /**
     * Like `ai_move`, but searches within a soft time budget (milliseconds)
     * using iterative deepening instead of a fixed depth.
     */
    func aiMoveTimed(maxDepth: UInt8, timeMs: UInt64) throws  -> MoveData
    
    func evaluate()  -> Int32
    
    func getCells()  -> [CellState]
    
    func getState()  -> GameState
    
    /**
     * Get a PGN metadata tag value, if present.
     */
    func getTag(key: String)  -> String?
    
    func legalMoves()  -> [MoveData]
    
    func loadFen(fen: String) throws 
    
    /**
     * Load a game from a PGN string. Resets the board (or starts from a `FEN`
     * tag when present) and replays the movetext.
     */
    func loadPgn(pgn: String) throws 
    
    func makeMove(fromSquare: UInt8, toSquare: UInt8, promotion: PieceKind?) throws  -> GameState
    
    /**
     * The SAN move list played so far (useful for reflecting a loaded game).
     */
    func moves()  -> [String]
    
    func reset() 
    
    /**
     * Serialize the current game to a PGN string.
     */
    func savePgn()  -> String
    
    /**
     * Set a PGN metadata tag (e.g. player names, event, date).
     */
    func setTag(key: String, value: String) 
    
    func undoMove() throws  -> GameState
    
}
open class ChessGame: ChessGameProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_engine_ffi_fn_clone_chessgame(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_constructor_chessgame_new(uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_engine_ffi_fn_free_chessgame(handle, $0) }
    }

    

    
open func aiMove(depth: UInt8)throws  -> MoveData  {
    return try  FfiConverterTypeMoveData_lift(try rustCallWithError(FfiConverterTypeChessError_lift) {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_ai_move(
            self.uniffiCloneHandle(),
        FfiConverterUInt8.lower(depth),uniffiCallStatus
    )
})
}
    
    /**
     * Like `ai_move`, but searches within a soft time budget (milliseconds)
     * using iterative deepening instead of a fixed depth.
     */
open func aiMoveTimed(maxDepth: UInt8, timeMs: UInt64)throws  -> MoveData  {
    return try  FfiConverterTypeMoveData_lift(try rustCallWithError(FfiConverterTypeChessError_lift) {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_ai_move_timed(
            self.uniffiCloneHandle(),
        FfiConverterUInt8.lower(maxDepth),
        FfiConverterUInt64.lower(timeMs),uniffiCallStatus
    )
})
}
    
open func evaluate() -> Int32  {
    return try!  FfiConverterInt32.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_evaluate(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func getCells() -> [CellState]  {
    return try!  FfiConverterSequenceTypeCellState.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_get_cells(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func getState() -> GameState  {
    return try!  FfiConverterTypeGameState_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_get_state(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Get a PGN metadata tag value, if present.
     */
open func getTag(key: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_get_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(key),uniffiCallStatus
    )
})
}
    
open func legalMoves() -> [MoveData]  {
    return try!  FfiConverterSequenceTypeMoveData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_legal_moves(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func loadFen(fen: String)throws   {try rustCallWithError(FfiConverterTypeChessError_lift) {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_load_fen(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(fen),uniffiCallStatus
    )
}
}
    
    /**
     * Load a game from a PGN string. Resets the board (or starts from a `FEN`
     * tag when present) and replays the movetext.
     */
open func loadPgn(pgn: String)throws   {try rustCallWithError(FfiConverterTypeChessError_lift) {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_load_pgn(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(pgn),uniffiCallStatus
    )
}
}
    
open func makeMove(fromSquare: UInt8, toSquare: UInt8, promotion: PieceKind?)throws  -> GameState  {
    return try  FfiConverterTypeGameState_lift(try rustCallWithError(FfiConverterTypeChessError_lift) {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_make_move(
            self.uniffiCloneHandle(),
        FfiConverterUInt8.lower(fromSquare),
        FfiConverterUInt8.lower(toSquare),
        FfiConverterOptionTypePieceKind.lower(promotion),uniffiCallStatus
    )
})
}
    
    /**
     * The SAN move list played so far (useful for reflecting a loaded game).
     */
open func moves() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_moves(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func reset()  {try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_reset(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}
    
    /**
     * Serialize the current game to a PGN string.
     */
open func savePgn() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_save_pgn(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * Set a PGN metadata tag (e.g. player names, event, date).
     */
open func setTag(key: String, value: String)  {try! rustCall() {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_set_tag(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(key),
        FfiConverterString.lower(value),uniffiCallStatus
    )
}
}
    
open func undoMove()throws  -> GameState  {
    return try  FfiConverterTypeGameState_lift(try rustCallWithError(FfiConverterTypeChessError_lift) {
        uniffiCallStatus in
    uniffi_engine_ffi_fn_method_chessgame_undo_move(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChessGame: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ChessGame

    public static func lift(_ handle: UInt64) throws -> ChessGame {
        return ChessGame(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ChessGame) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChessGame {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ChessGame, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChessGame_lift(_ handle: UInt64) throws -> ChessGame {
    return try FfiConverterTypeChessGame.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChessGame_lower(_ value: ChessGame) -> UInt64 {
    return FfiConverterTypeChessGame.lower(value)
}




public struct CellState: Equatable, Hashable {
    public var square: UInt8
    public var side: Side?
    public var kind: PieceKind?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(square: UInt8, side: Side?, kind: PieceKind?) {
        self.square = square
        self.side = side
        self.kind = kind
    }

    

    
}

#if compiler(>=6)
extension CellState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCellState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CellState {
        return
            try CellState(
                square: FfiConverterUInt8.read(from: &buf), 
                side: FfiConverterOptionTypeSide.read(from: &buf), 
                kind: FfiConverterOptionTypePieceKind.read(from: &buf)
        )
    }

    public static func write(_ value: CellState, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.square, into: &buf)
        FfiConverterOptionTypeSide.write(value.side, into: &buf)
        FfiConverterOptionTypePieceKind.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCellState_lift(_ buf: RustBuffer) throws -> CellState {
    return try FfiConverterTypeCellState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCellState_lower(_ value: CellState) -> RustBuffer {
    return FfiConverterTypeCellState.lower(value)
}


public struct GameState: Equatable, Hashable {
    public var fen: String
    public var turn: Side
    public var isInCheck: Bool
    public var isCheckmate: Bool
    public var isStalemate: Bool
    public var isDraw: Bool
    public var evaluationCp: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fen: String, turn: Side, isInCheck: Bool, isCheckmate: Bool, isStalemate: Bool, isDraw: Bool, evaluationCp: Int32) {
        self.fen = fen
        self.turn = turn
        self.isInCheck = isInCheck
        self.isCheckmate = isCheckmate
        self.isStalemate = isStalemate
        self.isDraw = isDraw
        self.evaluationCp = evaluationCp
    }

    

    
}

#if compiler(>=6)
extension GameState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGameState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GameState {
        return
            try GameState(
                fen: FfiConverterString.read(from: &buf), 
                turn: FfiConverterTypeSide.read(from: &buf), 
                isInCheck: FfiConverterBool.read(from: &buf), 
                isCheckmate: FfiConverterBool.read(from: &buf), 
                isStalemate: FfiConverterBool.read(from: &buf), 
                isDraw: FfiConverterBool.read(from: &buf), 
                evaluationCp: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: GameState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.fen, into: &buf)
        FfiConverterTypeSide.write(value.turn, into: &buf)
        FfiConverterBool.write(value.isInCheck, into: &buf)
        FfiConverterBool.write(value.isCheckmate, into: &buf)
        FfiConverterBool.write(value.isStalemate, into: &buf)
        FfiConverterBool.write(value.isDraw, into: &buf)
        FfiConverterInt32.write(value.evaluationCp, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGameState_lift(_ buf: RustBuffer) throws -> GameState {
    return try FfiConverterTypeGameState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGameState_lower(_ value: GameState) -> RustBuffer {
    return FfiConverterTypeGameState.lower(value)
}


public struct MoveData: Equatable, Hashable {
    public var fromSquare: UInt8
    public var toSquare: UInt8
    public var promotion: PieceKind?
    public var isCapture: Bool
    public var san: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(fromSquare: UInt8, toSquare: UInt8, promotion: PieceKind?, isCapture: Bool, san: String) {
        self.fromSquare = fromSquare
        self.toSquare = toSquare
        self.promotion = promotion
        self.isCapture = isCapture
        self.san = san
    }

    

    
}

#if compiler(>=6)
extension MoveData: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMoveData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MoveData {
        return
            try MoveData(
                fromSquare: FfiConverterUInt8.read(from: &buf), 
                toSquare: FfiConverterUInt8.read(from: &buf), 
                promotion: FfiConverterOptionTypePieceKind.read(from: &buf), 
                isCapture: FfiConverterBool.read(from: &buf), 
                san: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MoveData, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.fromSquare, into: &buf)
        FfiConverterUInt8.write(value.toSquare, into: &buf)
        FfiConverterOptionTypePieceKind.write(value.promotion, into: &buf)
        FfiConverterBool.write(value.isCapture, into: &buf)
        FfiConverterString.write(value.san, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoveData_lift(_ buf: RustBuffer) throws -> MoveData {
    return try FfiConverterTypeMoveData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMoveData_lower(_ value: MoveData) -> RustBuffer {
    return FfiConverterTypeMoveData.lower(value)
}


public 
enum ChessError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case IllegalMove
    case InvalidFen(reason: String
    )
    case InvalidPgn(reason: String
    )
    case GameOver
    case NothingToUndo

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ChessError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChessError: FfiConverterRustBuffer {
    typealias SwiftType = ChessError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChessError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .IllegalMove
        case 2: return .InvalidFen(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidPgn(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .GameOver
        case 5: return .NothingToUndo

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ChessError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .IllegalMove:
            writeInt(&buf, Int32(1))
        
        
        case let .InvalidFen(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidPgn(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .GameOver:
            writeInt(&buf, Int32(4))
        
        
        case .NothingToUndo:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChessError_lift(_ buf: RustBuffer) throws -> ChessError {
    return try FfiConverterTypeChessError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChessError_lower(_ value: ChessError) -> RustBuffer {
    return FfiConverterTypeChessError.lower(value)
}



public enum PieceKind: Equatable, Hashable {
    
    case pawn
    case knight
    case bishop
    case rook
    case queen
    case king





}

#if compiler(>=6)
extension PieceKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePieceKind: FfiConverterRustBuffer {
    typealias SwiftType = PieceKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PieceKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pawn
        
        case 2: return .knight
        
        case 3: return .bishop
        
        case 4: return .rook
        
        case 5: return .queen
        
        case 6: return .king
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PieceKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .pawn:
            writeInt(&buf, Int32(1))
        
        
        case .knight:
            writeInt(&buf, Int32(2))
        
        
        case .bishop:
            writeInt(&buf, Int32(3))
        
        
        case .rook:
            writeInt(&buf, Int32(4))
        
        
        case .queen:
            writeInt(&buf, Int32(5))
        
        
        case .king:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePieceKind_lift(_ buf: RustBuffer) throws -> PieceKind {
    return try FfiConverterTypePieceKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePieceKind_lower(_ value: PieceKind) -> RustBuffer {
    return FfiConverterTypePieceKind.lower(value)
}




public enum Side: Equatable, Hashable {
    
    case white
    case black





}

#if compiler(>=6)
extension Side: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSide: FfiConverterRustBuffer {
    typealias SwiftType = Side

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Side {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .white
        
        case 2: return .black
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Side, into buf: inout [UInt8]) {
        switch value {
        
        
        case .white:
            writeInt(&buf, Int32(1))
        
        
        case .black:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSide_lift(_ buf: RustBuffer) throws -> Side {
    return try FfiConverterTypeSide.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSide_lower(_ value: Side) -> RustBuffer {
    return FfiConverterTypeSide.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePieceKind: FfiConverterRustBuffer {
    typealias SwiftType = PieceKind?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePieceKind.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePieceKind.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSide: FfiConverterRustBuffer {
    typealias SwiftType = Side?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSide.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSide.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeCellState: FfiConverterRustBuffer {
    typealias SwiftType = [CellState]

    public static func write(_ value: [CellState], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeCellState.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [CellState] {
        let len: Int32 = try readInt(&buf)
        var seq = [CellState]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeCellState.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMoveData: FfiConverterRustBuffer {
    typealias SwiftType = [MoveData]

    public static func write(_ value: [MoveData], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMoveData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MoveData] {
        let len: Int32 = try readInt(&buf)
        var seq = [MoveData]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMoveData.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_engine_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_ai_move() != 22731) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_ai_move_timed() != 1793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_evaluate() != 36346) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_get_cells() != 38539) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_get_state() != 4803) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_get_tag() != 19700) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_legal_moves() != 59920) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_load_fen() != 11107) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_load_pgn() != 16554) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_make_move() != 47278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_moves() != 39728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_reset() != 25546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_save_pgn() != 19368) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_set_tag() != 48079) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_method_chessgame_undo_move() != 36898) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_ffi_checksum_constructor_chessgame_new() != 35759) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureEngineFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all